spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/alfc
    username: alfc
    password: alfc
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update

logging:
  level:
    com.example.Alfc: DEBUG
